name: drupal-lando-starterkit
recipe: drupal8
env_file:
  - .lando/.blackfire.env
config:
  webroot: web
  php: '7.4'
  via: nginx
  database: mysql:5.7
  xdebug: true
  config:
    database: drupal8
    username: drupal8
    password: drupal8
    host: database
    # for mysql
    port: 3306
services:
  appserver:
    overrides:
      build: ./.lando
      image: landophp-blackfire:7.4-fpm-2
    scanner: false
    build_as_root:
      - sed -i 's/^blackfire.agent_socket.*/blackfire.agent_socket\=tcp:\/\/blackfire:8307/' /usr/local/etc/php/conf.d/zz-blackfire.ini
    build:
      - cd /app/web/ && composer install
    run:
      - cp /app/web/sites/default/default.settings.local.php /app/web/sites/default/settings.local.php
      - cd /app/web/ && drush sql-cli < ../db_dump/drupal.sql
      - cd /app/web/ && drush cr
    config:
      php: .lando/config/php/php.ini
  blackfire:
    type: compose
    myUser: blackfire
    services:
      image: blackfire/blackfire:2
      command: blackfire agent
    overrides:
      ports:
        - 8307
